# Site settings
title: XIAOGUI
description: '小鬼 - 清风湿润，茶烟轻扬。 重温旧梦，故人已去。'
url: 'https://'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'mr_xiaogui'
  email: mr_xiaogui@163.com
  twitter_username: mr_xiaogui
  facebook_username: yangzuogui
  github_username:  xiaoguigit
  linkedin_username:  mr_xiaogui

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
